[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve -s dist"
healthcheckPath = "/"
multiRegionConfig = {"us-east-1":{"numReplicas":1}}
healthcheckTimeout = 5000
restartPolicyType = "never"